import React from 'react';

interface PageTermsProps {
  isOpen: boolean;
  onClose: () => void;
  onLogoClick?: () => void;
}

export const PageTerms: React.FC<PageTermsProps> = ({ isOpen, onClose, onLogoClick }) => {
  return (
    <div className={`page-panel ${isOpen ? 'open' : ''}`}>
      <div className="page-panel-header">
        <button className="page-watermark-logo" onClick={onLogoClick || onClose}>
          SEPEINT
        </button>
        <button className="page-panel-close" onClick={onClose} aria-label="Close">
          <span>CLOSE</span>
          <span className="page-panel-close-x">✕</span>
        </button>
      </div>

      <div className="page-panel-inner" style={{ marginTop: '50px' }}>
        <div className="page-label" style={{ letterSpacing: '0.3em', marginBottom: '32px' }}>[ DEPLOYMENT CONTRACTS ]</div>

        <h1 className="page-h1" style={{ letterSpacing: '-0.01em', marginBottom: '45px' }}>
          TERMS OF<br />
          <span className="page-h1-stroke">SERVICE</span>
        </h1>

        <div className="page-divider" style={{ margin: '45px 0' }} />

        <div className="page-two-col" style={{ gap: '80px' }}>
          <div className="page-col-left" style={{ display: 'flex', flexDirection: 'column', gap: '32px' }}>
            <div className="page-section-tag" style={{ letterSpacing: '0.2em', marginBottom: '8px' }}>AGREEMENT OVERVIEW</div>
            <p className="page-body" style={{ letterSpacing: '0.08em', color: 'rgba(255,255,255,0.85)', lineHeight: '1.8' }}>
              These Terms of Service govern your relationship, codebase ownership contracts, and system access constraints when you utilize software written or hosted by Sepeint.
            </p>
            <p className="page-body" style={{ letterSpacing: '0.08em', color: 'rgba(255,255,255,0.5)' }}>
              By accessing this site, requesting development specs, or deploying codebases generated by Sepeint, you accept these terms in full.
            </p>

            <h3 style={{ fontFamily: 'Bebas Neue', fontSize: '1.5rem', color: '#fff', marginTop: '20px', letterSpacing: '0.05em' }}>1. INTELLECTUAL PROPERTY & CODE OWNERSHIP</h3>
            <p className="page-body" style={{ letterSpacing: '0.08em', color: 'rgba(255,255,255,0.6)' }}>
              Sepeint guarantees 100% intellectual property and full source code handoff to clients upon final contract balance fulfillment. All custom database schemas, frontends, APIs, and AI automation workflows built under a specific development SLA are the absolute property of the client.
            </p>

            <h3 style={{ fontFamily: 'Bebas Neue', fontSize: '1.5rem', color: '#fff', marginTop: '20px', letterSpacing: '0.05em' }}>2. API USAGE & CODE MODIFICATIONS</h3>
            <p className="page-body" style={{ letterSpacing: '0.08em', color: 'rgba(255,255,255,0.6)' }}>
              Clients assume full operational control of custom servers and database structures post-deployment. Sepeint is not responsible for platform downtime resulting from external third-party API changes, custom client script modifications, or unmonitored Stripe webhook configurations.
            </p>

            <h3 style={{ fontFamily: 'Bebas Neue', fontSize: '1.5rem', color: '#fff', marginTop: '20px', letterSpacing: '0.05em' }}>3. NDA & CONFIDENTIALITY</h3>
            <p className="page-body" style={{ letterSpacing: '0.08em', color: 'rgba(255,255,255,0.6)' }}>
              All technical parameters, code directories, and corporate databases accessed during integrations are treated as strictly confidential under active non-disclosure agreements (NDA).
            </p>
          </div>

          <div className="page-col-right" style={{ borderLeft: '1px solid rgba(255,255,255,0.08)', paddingLeft: '48px', display: 'flex', flexDirection: 'column', gap: '30px' }}>
            <div className="page-section-tag" style={{ letterSpacing: '0.2em', marginBottom: '8px' }}>GOVERNANCE JURISDICTION</div>
            <div className="page-stat-block" style={{ borderTop: '1px solid rgba(255,255,255,0.15)', paddingTop: '20px' }}>
              <div className="page-stat-number" style={{ fontSize: '1.4rem', color: '#fff', marginBottom: '4px' }}>JURISDICTION</div>
              <div className="page-stat-label" style={{ letterSpacing: '0.12em' }}>BANGALORE REGIONAL COURT</div>
            </div>
            <div className="page-stat-block" style={{ borderTop: '1px solid rgba(255,255,255,0.15)', paddingTop: '20px' }}>
              <div className="page-stat-number" style={{ fontSize: '1.4rem', color: '#fff', marginBottom: '4px' }}>CONTRACT BASIS</div>
              <div className="page-stat-label" style={{ letterSpacing: '0.12em' }}>SOW AND NDAS SYSTEM</div>
            </div>
            <div className="page-stat-block" style={{ borderTop: '1px solid rgba(255,255,255,0.15)', paddingTop: '20px' }}>
              <div className="page-stat-number" style={{ fontSize: '1.4rem', color: '#fff', marginBottom: '4px' }}>SLA RUNTIME</div>
              <div className="page-stat-label" style={{ letterSpacing: '0.12em' }}>MUTUALLY AGREED MONTHLY RUN</div>
            </div>
          </div>
        </div>

        <div className="page-divider" style={{ margin: '45px 0' }} />

        <div className="page-footer-row">
          <div className="page-footer-text">SEPEINT · BANGALORE, INDIA</div>
          <div className="page-footer-text">contact.sepeint@gmail.com</div>
        </div>
      </div>
    </div>
  );
};
